# Generated by Django 5.0.4 on 2024-04-30 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'maintenance_type',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machine', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('description', models.TextField()),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancetype')),
            ],
            options={
                'db_table': 'maintenance',
            },
        ),
    ]
