# Generated by Django 5.0.4 on 2024-04-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SensorID', models.TextField()),
                ('Date_n_Time', models.TextField()),
                ('A', models.TextField()),
            ],
            options={
                'db_table': 'A_Data',
            },
        ),
        migrations.CreateModel(
            name='BData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SensorID', models.TextField()),
                ('Date_n_Time', models.TextField()),
                ('B', models.TextField()),
            ],
            options={
                'db_table': 'B_Data',
            },
        ),
        migrations.CreateModel(
            name='WData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SensorID', models.TextField()),
                ('Date_n_Time', models.TextField()),
                ('W', models.TextField()),
            ],
            options={
                'db_table': 'W_Data',
            },
        ),
        migrations.CreateModel(
            name='XData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SensorID', models.TextField()),
                ('Date_n_Time', models.TextField()),
                ('X', models.TextField()),
            ],
            options={
                'db_table': 'X_Data',
            },
        ),
        migrations.CreateModel(
            name='YData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SensorID', models.TextField()),
                ('Date_n_Time', models.TextField()),
                ('Y', models.TextField()),
            ],
            options={
                'db_table': 'Y_Data',
            },
        ),
        migrations.CreateModel(
            name='ZData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SensorID', models.TextField()),
                ('Date_n_Time', models.TextField()),
                ('Z', models.TextField()),
            ],
            options={
                'db_table': 'Z_Data',
            },
        ),
    ]
