# Generated by Django 5.0.4 on 2024-04-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SensorID', models.TextField()),
                ('Date_n_Time', models.TextField()),
                ('Z', models.TextField()),
            ],
            options={
                'db_table': 'L_Data',
            },
        ),
    ]
